### ISSUE TITLE
Agent status Available while on contact

### ISSUE THREAD

**Issue by CBVTorrijos** [aws-samples/aws-serverless-connect-wallboard#14]
Hello,

I noticed there was a closed issue in regards to this as it is limited with connect. Do you happen to know if anything has come about talking to support about this? Also, any workaround so far that has been formulated to get this showing as "On Contact" instead of Available?

**Comment by Brettles** [comment]
I don't have an easy workaround here because the wallboard is limited (as it's written) to show the status of each agent as it is sent via Kinesis.

Looking at the [various states](https://docs.aws.amazon.com/connect/latest/adminguide/metrics-agent-status.html) there are definitely some other states that agents can be in and those are reflected in the reports but aren't emitted as events to Kinesis. Because they're in the reports they may be something that is inferred from other data at a later stage and not available in real-time.

As per the other issue: If you have a way of detecting a set of agent states (or even just one) it's a simple matter to put that into the DynamoDB table. The hard part is the detection/decision. From there, you could either write to the table directly or have an external process call an API to do it for you.

**Comment by Brettles** [comment]
It's been a long time but I think this is now fixed - there's an update to `process-agent-event.py` - please try that because it has additional agent states.

**Comment by CBVTorrijos** [comment]
Thanks Brett! I will give it a try!

**Comment by CBVTorrijos** [comment]
@Brettles This has fixed the issue we were having, this is magnificent! Great work and update this helps our agents!
