### ISSUE TITLE
Dynamically Display of Agent 

### ISSUE THREAD

**Issue by Aikleong7** [aws-samples/aws-serverless-connect-wallboard#15]
I realize that only can display a limited number of agents if there are not enough cells, I'm having large number of agents and the display of agent is not dynamic to the agents active and also how do I display agent's information like Agent's Avg ACW and Duration.

**Comment by Brettles** [comment]
Have you tried using `=activeagents` instead of agents names? Only active agent names will then be put into the output.

AFAIK there's no easy way to determine the average wait time or call duration per agent. Connect doesn't publish metrics for each agent but it *might* be something that can be calculated by going through the [Contact Trace Record](https://docs.aws.amazon.com/connect/latest/adminguide/ctr-data-model.html) data. One challenge I see there is that it would be historical and not real-time - the CTRs aren't available until after a call/contact is complete.

Another challenge is that in order to get the average call waiting or duration you'd need to calculate that across a specific historical period (last hour? last day? last shift?) and that data would need to be stored somewhere in order to be performant for the dashboard.

I'll have a think about it and see if there's something that can be done there.

**Comment by Aikleong7** [comment]
I tried using =activeagents but if there are only 3 cells defined only will have 3 agents displayed but if i have 100 agents active it cannot display all. And also maybe can display the avg handle time or call handled by the agents. Is it possible for that?

**Comment by Brettles** [comment]
Unfortunately (today) you need to define the cells where you want data. So if you wanted to display (say) 50 agent details then you'd need to have 50 cells each with `=activeagents` in them.

Also, individual data per agent isn't available - including calls handled by each agent. Same as above - it's something that can probably be derived from the CTR data but it's not simple to do.

We are working on some enhancements - one of them may give you another way of displaying the agent data. Stay tuned.

**Comment by Aikleong7** [comment]
Sure. Do update me as well!

**Comment by Brettles** [comment]
Pushed an update today. It's probably not exactly what you want (because it requires change on your side) but an idea:

You can now call the API and request JSON output rather than a preformatted HTML table. So what you could do is define a wallboard just for agents - have hundreds or thousands of cells if you like; then call the API to retrieve the wallboard (just put `json=true` on the end of the API call) and then parse at the front end and render how you like.

Let me know if that helps.
